export const designRoles = [
  {
    name: "SENIOR PRODUCT MANAGER",
    desc: "We are looking for Senior Product Managers to join our growing team.",
    jobType: "Full-time",
    dept: "dm",
    link: "",
    id: "role1",
    idx: 0,
    posDesc:
      "Our product Managers own the end-to-end planning and execution of products, develop and execute the product strategy. Product managers are responsible for driving product choices and priorities in partnership with all stakeholders. Roles and Responsibilities includes but not limited to:",
    responsibilities: [
      "Strive to deeply understand user needs by conducting user research and identifying opportunities and pain points. And advocate for user needs through the cycle of building products.",
      "Define, document, and drive roadmaps, project plans, and precise product specifications that consistently deliver quality products for your customers.",
      "Work with a team of engineers and designers to discover solutions to customer pain points, and build and launch products for local and global businesses.",
      "Define and drive roadmaps, project plans, and precise product specifications that consistently deliver quality products.",
      "Ensure successful product launches by working cross-functionally with marketing, merchant success, sales, operations, legal, and compliance teams. Requirements",
    ],
    qualifications: [
      "4+ years of experience in product management, with demonstrated experience in successfully building and shipping impactful products.",
      "Strong strategic thinking, and problem-solving abilities.",
      "You have a good understanding of how software is built and operated and experience in building technical software products.",
      "Strong customer empathy and experience shaping product direction and execution based on customer needs.",
      "Excellent ability to bring clarity and focus to complex and ambiguous situations.",
      "Excellent verbal and written communication skills.",
      "Ability to collaborate.",
      "Great attention to detail and cares about building quality products.",
      "Experience working with both qualitative customer insights and quantitative data to inform decisions.",
    ],
  },
];
export const devRoles = [
  {
    name: "SENIOR FRONT-END DEVELOPER",
    desc: "An experienced React developer is needed for a full time role.",
    jobType: "Full-time",
    link: "",
    dept: "dev",
    idx: 0,
    id: "role2",
    posDesc:
      "As a React.js Developer, you are expected to have Hands on experience developing Web based UI using Javascript/Typescript/ReactJS. You will be involved from conception to completion with projects that are technologically sound and aesthetically impressive. Duties and responsibilities include but not limited to:",
    responsibilities: [
      "Writing codes to develop highly-responsive, web-based user interface",
      "Collaborate with team members and business partners for problem solving, bug fixes, new feature implementations, work planning and code demonstrations.",
      "Assist with team-wide validation of functional correctness, architectural compliance, and adherence to applicable industry standards.",
      "Develop a flexible and well-structured front-end architecture, along with the APIs to support it.",
      "Collaborate with other teams to coordinate changes to shared interfaces.",
      "Collaborate with other teams to coordinate changes to shared interfaces.",
      "Adhere to team standards for writing and documenting code.",
    ],
    qualifications: [
      "Firm understanding of Object Oriented principles, design patterns, and software design/architecture best practices.",
      "Ability to communicate technical concepts clearly concisely both verbally and in writing.",
      "Ability to collaboratively work through technical issues in a professional manner, making design considerations and trade-offs as needed.",
      "Thrive in and contribute to a collaborative team environment.",
      "Working knowledge on debugging problems using relevant tools.",
      "Experience with JavaScript, Typescript, Redux, RTK Query, Styled Components.",
    ],
  },
  {
    name: "JUNIOR FRONT-END DEVELOPER",
    desc: "We’re looking for a junior frontend developer to join our team.",
    jobType: "Full-time",
    link: "",
    dept: "dev",
    id: "role3",
    idx: 1,
    posDesc:
      "As a React.js Developer, you will be involved from conception to completion with projects that are technologically sound and aesthetically impressive. Duties and responsibilities include but not limited to:",
    responsibilities: [
      "Responsible for development of new highly-responsive, web-based user interface.",
      "Collaborate with team members and business partners for problem solving, bug fixes, new feature implementations, work planning and code demonstrations.",
      "Work and collaborate with the rest of the engineering team.",
      "Work with product team and graphic designers.",
      "Develop a flexible and well-structured front-end architecture, along with the APIs to support it.",
      "Adhere to team standards for writing and documenting code.",
    ],
    qualifications: [
      "Minimum of 1yr of experience in React.js.",
      "Experience with JavaScript, Typescript, Redux, RTK Query, Styled Components.",
      "Working knowledge of Git.",
      "Experience of Fintech app is a plus.",
      "Great interpersonal and communication skills.",
    ],
  },
  {
    name: "SENIOR BACK-END JAVA DEVELOPER",
    desc: "We’re looking for an experienced backend java developer to join our team.",
    jobType: "Full-time",
    link: "",
    dept: "dev",
    idx: 2,
    id: "role4",
    posDesc:
      "As a back-end Java Developer, your roles and responsibilities include but not limited to:",
    responsibilities: [
      "Supporting the development of enterprise applications.",
      "Independently identify technical solutions for business problems, directly contribute to conceptual design, and routinely collaborate with Enterprise/Application architects, Database.",
      "Designing and implementing micro-services architectures.",
      "Independently identify technical solutions for business problems, directly contribute to conceptual design, and routinely collaborate with Enterprise/Application architects, Database.",
    ],
    qualifications: [
      "Proficiency in Java, with a good understanding of its ecosystems.",
      "Sound knowledge of Object-Oriented Programming (OOP) Patterns and Concepts.",
      "Familiarity with different design and architectural patterns.",
      "Skill for writing reusable Java libraries and know-how of Java concurrency pattern.",
      "Basic Understanding of the concepts of MVC (Model-View-Controller) Pattern, JDBC (Java Database Connectivity), and RESTful web services.",
      "Relevant Knowledge of Java GUI frameworks according to project requirements.",
      "Experience in handling external and embedded databases.",
      "Understanding basic design principles behind a scalable application.",
      "Skilled at creating database schemas that characterize and support business processes.",
      "In-depth knowledge of code versioning tools, for instance, Git.",
      "Expertise in continuous integration.",
    ],
  },
  {
    name: "SENIOR BACK-END NODE JS DEVELOPER",
    desc: "We’re looking for an experienced backend node developer to join our team.",
    jobType: "Full-time",
    link: "",
    dept: "dev",
    idx: 3,
    id: "role5",
    posDesc:
      "As a Backend Developer, your roles and responsibilities include but not limited to:",
    responsibilities: [
      "Using Nodejs server-side framework to implement a robust and scalable.",
      "Supporting the development of enterprise applications.",
      "Designing and implementing microservices architectures.",
      "Independently identify technical solutions for business problems, directly contribute to conceptual design, and routinely collaborate with Enterprise/Application architects, Database.",
    ],
    qualifications: [
      "Experience in cross-platform development with strong knowledge on Node.js.",
      "Familiarity with REST and integration concepts.",
      "Experience on implementing NFRs but not limited to Performance, Scalability, Availability, Maintainability and Security.",
      "Knowledge of Micro services and respective architecture design principles and scalability best practices.",
      "Experience developing APIs against database technologies (MySQL, Postgres).",
      "Strong background in Logic and Algorithms.",
      "Perform analysis, design, programming, and implementation on systems and procedures to solve complex business problems.",
      "Create review technical design documentation.",
      "Perform periodic code reviews according to programming and development standards and best practice.",
    ],
  },
];
